version: 0.2
env:
  variables:
    REACT_APP_DEMO_VAR: 'cliimate-accelerator'
phases:

  deploy:
    commands:
      - zip -r function.zip index.js package.json package-lock.json      
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name codepipeline_ci-cd --zip-file fileb://function.zip
      - echo "DONE!!"